---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: textarea
  name: description
  label: Description
- type: file
  name: preview
  label: Preview
pages:
- _posts/iron-man-watercolor.md
