---
label: Project
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
- type: textarea
  name: description
  label: Description
- type: file
  name: preview
  label: Preview
pages:
- _posts/test-title-three.md
- _posts/2019-02-27-test-title-two.md
