---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: textarea
  name: description
  label: Description
- name: categories
  type: tag_list
  default: []
  label: Categories
- type: file
  name: image
  label: Image
- name: layout
  type: text
  config:
    required: false
  label: Layout
  hidden: true
  default: post
pages:
- _posts/hawkeye-watercolor.md
- _posts/black-widow-watercolor.md
- _posts/thor-watercolor.md
- _posts/captain-america-watercolor.md
