---
label: Project
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
- type: textarea
  name: description
  label: Description
- type: file
  name: preview
  label: Preview
pages:
- _posts/five.md
- _posts/another-test-four.md
- _posts/2019-02-27-test-title-two.md
